### ISSUE TITLE
Ratelimiter problem on startup

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#161]
FREME failed to start with this message. It was a FREME distribution that I started via command line. 

```
...
Caused by: java.io.FileNotFoundException: file:/opt/freme/FREME-0.5/Broker-0.5.jar!/ratelimiter.yaml (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:115)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:159)
	... 38 more
```

When no ratelimiter.yml is found then FREME should start without ratelimiting.

The odd thing is that the ratelimiter.yaml was contained in the jar at the specified path. It was also placed in the root of the classpath.

I could start it by deleting the ratelimiter.yaml out of the jar archive.

**Comment by jnehring** [comment]
The problem does not occur anymore
