### ISSUE TITLE
epubcheck in e-publishing integration test

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#86]
@ArneBinder  introduced epubcheck for integration tests of e-publishing. However I hear that it reports errors but I cannot see the errors and I could not find documentation about these errors. This ticket is a reminder to not forget the issue. @ArneBinder please document the problems and ask @pheyvaer  about them. We have to find out if the errors originate from the buggy epubcheck library or from a buggy epub3 file.

One more problem with the library is that it causes a conflict with e-Internationalization. I removed this dependency from brokers pom.xml:
```
		<dependency>
			<groupId>org.idpf</groupId>
			<artifactId>epubcheck</artifactId>
			<version>3.0.1</version>
			<scope>test</scope>
		</dependency>
```

it produced this error:

```
ERROR   2015-08-25 16:16:48,118 [http-nio-8000-exec-1] eu.freme.i18n.okapi.nif.converter.NifConverter  - exception
java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/C:/Users/jnehring/.m2/repository/net/sf/saxon/Saxon-HE/9.4.0.6/Saxon-HE-9.4.0.6.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
	at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
	at net.sf.okapi.filters.its.Parameters.<init>(Parameters.java:130)
	at net.sf.okapi.filters.its.ITSFilter.<init>(ITSFilter.java:122)
	at net.sf.okapi.filters.xml.XMLFilter.<init>(XMLFilter.java:55)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.sf.okapi.common.filters.FilterConfigurationMapper.addConfigurations(FilterConfigurationMapper.java:594)
	at net.sf.okapi.common.filters.FilterConfigurationMapper.addConfigurations(FilterConfigurationMapper.java:136)
	at net.sf.okapi.lib.extra.pipelinebuilder.XDocument.<init>(XDocument.java:46)
	at net.sf.okapi.lib.extra.pipelinebuilder.XBatchItem.<init>(XBatchItem.java:55)
	at eu.freme.i18n.okapi.nif.converter.NifConverter.convert2Nif(NifConverter.java:78)
	at eu.freme.i18n.okapi.nif.converter.NifConverter.convert2Nif(NifConverter.java:261)
...
```

**Comment by jnehring** [comment]
* Please re-integrate epubcheck in a separate branch
* Run the validation
* report the errors in this github issue
* assign issue to @pheyvaer

**Comment by ArneBinder** [comment]
Re-integrated (see branch ebubcheck) and did not find any errors.

**Comment by ArneBinder** [comment]
The epubcheck version 4 does not conflict with e-Internationalization anymore. Furthermore the receved response from E-Publishing validates successfully with epubcheck. epubcheck is re-integrated into the master.
